name: OZIP Decrypter by TechyMinati... & Tweaked by sauraj

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  FIRMWARE_LINK: https://download.c.realme.com/osupdate/RMX2151PU_11_OTA_0830_all_AFFrwZpAzh0Z.ozip #edit link here...
  FIRMWARE_NAME: RMX2151PU_11_OTA_0830_all_AFFrwZpAzh0Z.ozip  #edit file name here, you can find the name of file from link itself...
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python-pip
             sudo -H pip install --upgrade pip
             sudo -H pip install setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             sudo python ozipdecrypt.py $FIRMWARE_NAME

       - name: ziping decrypted file
         run: |
             cd out
             sudo zip -r The_name_of_zip_you_want.zip * #edit this filename, or leave it unchanged.

       - name: Upload Decrypted zip
         run: |
             cd out
             curl https://bashupload.com/ -T *.zip #file will be uploaded to bashupload, so mirror it if you are decrypting for community uses.
